import type { RegressionCatalogCase } from './catalogTypes';

/**
 * 客户端回归 — Unity `StarCrystal.Client.Tests.EditMode` + `PlayMode`。
 * 与 `StarCrystal2022/doc/客户端测试用例.md` §6 / §K 及已实现测试类对齐。
 */
export const CLIENT_REGRESSION_CATALOG: RegressionCatalogCase[] = [
  // —— K. 福利任务 Edit ——
  {
    id: 'TSK-P-001',
    api: '（EditMode）解析 GET welfare JSON',
    servicePurpose: 'StarCrystalTaskHandler.TryWelfareResponse',
    verify: 'tierPolicy.p0Enabled',
    unityTest: 'TSK_P_001_WelfareResponse_ParsesTierPolicy',
    docRef: 'WelfareTaskHandlerEditModeTests',
  },
  {
    id: 'TSK-P-002',
    api: '（EditMode）解析 POST claim JSON',
    servicePurpose: 'TryClaimResponse',
    verify: 'grantedGold=50',
    unityTest: 'TSK_P_002_ClaimResponse_ParsesGrantedGold',
    docRef: 'WelfareTaskHandlerEditModeTests',
  },
  // —— K. 福利任务 Play ——
  {
    id: 'TSK-C-001',
    api: 'GET /api/v1/tasks/welfare',
    servicePurpose: 'WelfareTaskController · P0 任务列表',
    verify: 'tasks≥10；p0Enabled',
    unityTest: 'TSK_C_001_GetWelfare_ReturnsP0Tasks',
    docRef: 'WelfareTaskPlayModeTests',
  },
  {
    id: 'TSK-C-002',
    api: 'POST /api/v1/tasks/claim signin_7d',
    servicePurpose: '七日签到 · 会话 curgold',
    verify: 'grantedGold>0',
    unityTest: 'TSK_C_002_Signin7dClaim_UpdatesSessionGoldFromServer',
    docRef: 'WelfareTaskPlayModeTests',
  },
  {
    id: 'TSK-C-003',
    api: 'POST /api/v1/rank/activity',
    servicePurpose: 'play_daily_60s 活跃上报',
    verify: 'status=claimable',
    unityTest: 'TSK_C_003_PlayDaily60s_ClaimableAfterActivity',
    docRef: 'WelfareTaskPlayModeTests',
  },
  {
    id: 'TSK-C-004',
    api: 'ads/start + complete ×3',
    servicePurpose: 'ad_daily_3 进度',
    verify: 'claimable',
    unityTest: 'TSK_C_004_AdDaily3_ClaimableAfterThreeCompletions',
    docRef: 'WelfareTaskPlayModeTests',
  },
  {
    id: 'TSK-C-005',
    api: 'POST claim signin_7d adBonus',
    servicePurpose: '签到广告加成',
    verify: 'grantedGold 含 bonus',
    unityTest: 'TSK_C_005_Signin7d_AdBonus_OnFreshGuest_IncludesBonus',
    docRef: 'WelfareTaskPlayModeTests',
  },
  {
    id: 'TSK-C-006',
    api: '邀请注册 + claim daily_invite',
    servicePurpose: '邀请进度',
    verify: 'claimable',
    unityTest: 'TSK_C_006_DailyInvite_ClaimableAfterInviteRegister',
    docRef: 'WelfareTaskPlayModeTests',
  },
  {
    id: 'TSK-C-007',
    api: 'POST claim daily_invite（无邀请）',
    servicePurpose: '无进度不可领',
    verify: '业务失败',
    unityTest: 'TSK_C_007_DailyInvite_WithoutInvite_NotClaimable',
    docRef: 'WelfareTaskPlayModeTests',
  },
  {
    id: 'TSK-C-008',
    api: 'GET /api/v1/tasks/welfare + MoreTasksList.Refresh',
    servicePurpose: '更多任务列表 UI 布局',
    verify: '行数=CollectExtraTasks；列表/行高度>0；首行有标题',
    unityTest: 'TSK_C_008_MoreTasksList_RendersVisibleRows',
    docRef: 'WelfareTaskPlayModeTests',
  },
  {
    id: 'TSK-C-009',
    api: '（PlayMode）MoreTasksList 嵌套滚动',
    servicePurpose: 'WelfareTaskMoreListView 父/子 ScrollRect 接力',
    verify: '先滚外层至面板贴顶→内层列表→内层到底后继续滚外层',
    unityTest: 'TSK_C_009_NestedScroll_ParentThenInnerThenParent',
    docRef: 'WelfareNestedScrollPlayModeTests',
  },
  // —— B. 鉴权 Play ——
  {
    id: 'AUTH-I-001',
    api: 'POST /api/v1/auth/guest',
    servicePurpose: '游客登录 · PlayerPrefs',
    verify: 'accessToken；HasEstablishedServerSession',
    unityTest: 'GuestLogin_Succeeds_And_PersistsSession',
    docRef: 'AuthApiPlayModeTests',
  },
  {
    id: 'AUTH-I-002',
    api: 'POST /api/v1/auth/guest',
    servicePurpose: '同 deviceId + guestKey 复用 accountId',
    verify: '两次 accountId 相同',
    unityTest: 'GuestLogin_Twice_ReusesGuestKey',
    docRef: 'AuthApiPlayModeTests',
  },
  {
    id: 'AUTH-I-003',
    api: 'GET /api/v1/auth/me',
    servicePurpose: 'Bearer 查当前用户',
    verify: 'accountId 一致',
    unityTest: 'AuthMe_WithBearer_ReturnsUser',
    docRef: 'AuthApiPlayModeTests',
  },
  {
    id: 'AUTH-I-004',
    api: 'sendverificationcode + register',
    servicePurpose: 'SMS Mock 注册链',
    verify: '注册成功（可 Ignore 无 Mock）',
    unityTest: 'RegisterByCode_WithSmsMock_DevCode',
    docRef: 'AuthApiPlayModeTests',
  },
  {
    id: 'AUTH-I-005',
    api: 'POST /api/v1/auth/login',
    servicePurpose: '错误密码',
    verify: 'businessCode=1416',
    unityTest: 'Login_WrongPassword_Fails',
    docRef: 'AuthApiPlayModeTests',
  },
  {
    id: 'DEP-I-001',
    api: 'POST /api/v1/welfare/exchange',
    servicePurpose: '废弃兑换接口',
    verify: '410 + 1410',
    unityTest: 'WelfareExchange_Endpoint_Returns410',
    docRef: 'AuthApiPlayModeTests',
  },
  // —— A. 鉴权 Edit ——
  {
    id: 'AUTH-P-001',
    api: '（EditMode）游客 JSON',
    servicePurpose: 'TryFromAuthResponse',
    verify: 'accessToken + accountId',
    unityTest: 'TryFromAuthResponse_GuestSuccess_ParsesTokenAndUser',
    docRef: 'AuthHandlerEditModeTests',
  },
  {
    id: 'AUTH-P-002',
    api: '（EditMode）code!=0',
    servicePurpose: '业务错误信封',
    verify: 'success=false',
    unityTest: 'TryFromAuthResponse_BusinessError_ReturnsCode',
    docRef: 'AuthHandlerEditModeTests',
  },
  // —— E. 排行 Play ——
  {
    id: 'RNK-I-001',
    api: 'GET /api/v1/rank?board=popularity',
    servicePurpose: '人气榜',
    verify: 'code=0',
    unityTest: 'GetRank_Popularity_ReturnsEnvelope',
    docRef: 'RankApiPlayModeTests',
  },
  {
    id: 'RNK-I-002',
    api: 'GET rank welfare_gold_cur',
    servicePurpose: '福利金币榜',
    verify: 'items 非 null',
    unityTest: 'GetRank_WelfareGoldCur_ReturnsItemsOrEmpty',
    docRef: 'RankApiPlayModeTests',
  },
  {
    id: 'RNK-I-003',
    api: 'POST /api/v1/rank/play',
    servicePurpose: '人气 playCount',
    verify: 'playCount≥1',
    unityTest: 'PostRankPlay_IncrementsPopularity',
    docRef: 'RankApiPlayModeTests',
  },
  {
    id: 'RNK-I-004',
    api: 'GET rank activity week',
    servicePurpose: '活跃周榜',
    verify: 'activeScore / weekId',
    unityTest: 'GetRank_Activity_Week_ReturnsEnvelope',
    docRef: 'ActivityRankPlayModeTests',
  },
  {
    id: 'RNK-I-006',
    api: 'POST rank/activity + GET activity',
    servicePurpose: '活跃累计上榜',
    verify: '列表含 gameId',
    unityTest: 'ReportRankActivity_ThenGetRank_ListsAccountOnBoard',
    docRef: 'ActivityRankPlayModeTests',
  },
  {
    id: 'RNK-I-007',
    api: 'POST rank/activity <minSlice',
    servicePurpose: '短时长上报',
    verify: 'activeScore=0 仍 code=0',
    unityTest: 'ReportRankActivity_BelowMinSlice_ReturnsZeroScoreButOk',
    docRef: 'ActivityRankPlayModeTests',
  },
  // —— J. 经济 / 福利 Play ——
  {
    id: 'ECO-I-001',
    api: 'GM patch + GET welfare_gold_cur',
    servicePurpose: 'GM 改 curgold 同步榜与会话',
    verify: 'myScore≈curgold',
    unityTest: 'GmPatch_CurGold_ReflectsOnWelfareGoldCurRank',
    docRef: 'EconomyWelfarePlayModeTests',
  },
  {
    id: 'ECO-I-002',
    api: 'IDIP settlement',
    servicePurpose: '月末 force 结算 totalgold',
    verify: 'curgold=0；totalgold 增加',
    unityTest: 'MonthlySettlement_AfterGmGold_UpdatesTotalGoldAndRank',
    docRef: 'EconomyWelfarePlayModeTests',
  },
  {
    id: 'WEL-I-003',
    api: 'POST redeem-token-gift',
    servicePurpose: 'GetToken 兑换',
    verify: 'curtoken=0；totaltoken 增加',
    unityTest: 'GetTokenButton_Redeem_UpdatesCurAndTotalTokenRanks',
    docRef: 'EconomyWelfarePlayModeTests',
  },
  // —— L. UI 端到端（加载场景 + 点击控件）——
  {
    id: 'UI-E2E-001',
    api: 'LoginScene GuestLoginBtn',
    servicePurpose: '游客 UI 进主场景',
    verify: 'MainScene + Session',
    unityTest: 'UI_E2E_001_LoginScene_GuestButton_EntersMainScene',
    docRef: 'ClientUiE2EPlayModeTests',
  },
  {
    id: 'UI-E2E-006',
    api: 'Welfare GetTokenButton',
    servicePurpose: '提取 Token 全链路',
    verify: 'HUD curtoken→0；会话 totaltoken',
    unityTest: 'UI_E2E_006_Welfare_GetTokenButton_FullChain_UpdatesHudAndSession',
    docRef: 'ClientUiE2EPlayModeTests',
  },
  // —— D/G. 排行 · 配置 Edit ——
  {
    id: 'RNK-P-002',
    api: '（EditMode）welfare_gold_cur JSON',
    servicePurpose: 'RankHandler 解析 myRank/gold',
    verify: 'double 字段',
    unityTest: 'TryFromRankListResponse_WelfareGoldCur_WithMyRankAndDoubles',
    docRef: 'RankHandlerEditModeTests',
  },
  {
    id: 'RNK-P-005',
    api: '（EditMode）activity week JSON',
    servicePurpose: '活跃榜解析',
    verify: 'activeScore',
    unityTest: 'TryFromRankListResponse_Activity_Week_WithActiveScore',
    docRef: 'RankHandlerEditModeTests',
  },
  {
    id: 'CFG-P-001',
    api: '（EditMode）ApiBaseUrl',
    servicePurpose: 'StarCrystalConfig',
    verify: '非空',
    unityTest: 'ApiBaseUrl_IsConfigured',
    docRef: 'ConfigEditModeTests',
  },
  {
    id: 'SES-P-001',
    api: '（EditMode）StarCrystalSession.Save',
    servicePurpose: 'PlayerPrefs 会话',
    verify: 'HasEstablishedServerSession',
    unityTest: 'Save_SetsEstablishedServerSession',
    docRef: 'SessionEditModeTests',
  },
  {
    id: 'WEL-P-001',
    api: '（EditMode）redeem-token-gift JSON',
    servicePurpose: '兑换响应解析',
    verify: 'curtoken/totaltoken',
    unityTest: 'RedeemTokenGift_Succeeds_ParsesEconomyFields',
    docRef: 'WelfareRedeemEditModeTests',
  },
  {
    id: 'RNK-P-006',
    api: '（EditMode）POST rank/activity JSON',
    servicePurpose: 'StarCrystalRankHandler.TryFromRankActivityResponse',
    verify: 'activeScore / weekId',
    unityTest: 'TryFromRankActivityResponse_Success',
    docRef: 'RankHandlerEditModeTests',
  },
  // —— M. 游戏收藏 Edit ——
  {
    id: 'FAV-P-001',
    api: '（EditMode）POST favorite JSON',
    servicePurpose: 'TryFromToggleResponse',
    verify: 'gameId + favorited=true',
    unityTest: 'FAV_P_001_ToggleResponse_ParsesSuccess',
    docRef: 'GameFavoriteHandlerEditModeTests',
  },
  {
    id: 'FAV-P-002',
    api: '（EditMode）GET favorites JSON',
    servicePurpose: 'TryFromListResponse',
    verify: 'gameIds[] 不丢项',
    unityTest: 'FAV_P_002_ListResponse_ParsesGameIds',
    docRef: 'GameFavoriteHandlerEditModeTests',
  },
  {
    id: 'FAV-P-003',
    api: '（EditMode）favorite code!=0',
    servicePurpose: '业务错误信封',
    verify: 'success=false',
    unityTest: 'FAV_P_003_ToggleResponse_CodeNonZero_Fails',
    docRef: 'GameFavoriteHandlerEditModeTests',
  },
  {
    id: 'FAV-P-004',
    api: '（EditMode）非 JSON 405',
    servicePurpose: '旧服 Method Not Allowed 提示',
    verify: 'message 含 405',
    unityTest: 'FAV_P_004_NonJson_MethodNotAllowed_Hint',
    docRef: 'GameFavoriteHandlerEditModeTests',
  },
  {
    id: 'FAV-P-005',
    api: '（EditMode）health 占位 data.service',
    servicePurpose: '未部署 favorite 路由时解析失败',
    verify: '提示 rebuild',
    unityTest: 'FAV_P_005_ListResponse_OldServerStub_Fails',
    docRef: 'GameFavoriteHandlerEditModeTests',
  },
  // —— M. 游戏收藏 Play ——
  {
    id: 'FAV-I-001',
    api: 'POST /api/v1/games/favorite',
    servicePurpose: 'Bearer 添加收藏',
    verify: 'favorited=true',
    unityTest: 'FAV_I_001_AddFavorite_ReturnsFavoritedTrue',
    docRef: 'GameFavoriteApiPlayModeTests',
  },
  {
    id: 'FAV-I-002',
    api: 'GET /api/v1/games/favorites',
    servicePurpose: '收藏列表含 gameId',
    verify: '含 g002',
    unityTest: 'FAV_I_002_ListFavorites_ContainsGameId',
    docRef: 'GameFavoriteApiPlayModeTests',
  },
  {
    id: 'FAV-I-003',
    api: 'DELETE /api/v1/games/favorite',
    servicePurpose: '取消收藏后列表不含',
    verify: 'favorited=false',
    unityTest: 'FAV_I_003_RemoveFavorite_ThenNotInList',
    docRef: 'GameFavoriteApiPlayModeTests',
  },
  {
    id: 'FAV-I-004',
    api: '（PlayMode）GameFavoriteService',
    servicePurpose: 'SyncFavorites + Toggle → Registry',
    verify: 'IsFavorited 与 API 一致',
    unityTest: 'FAV_I_004_GameFavoriteService_SyncAndToggle_UpdatesRegistry',
    docRef: 'GameFavoriteApiPlayModeTests',
  },
  {
    id: 'FAV-I-005',
    api: 'GET /api/v1/games + Bearer',
    servicePurpose: '列表项 favorited 标记',
    verify: 'g002.favorited=true',
    unityTest: 'FAV_I_005_GetGameList_WithBearer_MarksFavorited',
    docRef: 'GameFavoriteApiPlayModeTests',
  },
];
