import type { RegressionCatalogCase } from './catalogTypes';

/**
 * 服务端回归 — `go test ./internal/api/ ./internal/service/` 任务 / IDIP / 活跃子集。
 * 与 `后台测试用例-v7.1.md` §I / §L 及 `server-go/internal/api/*_test.go` 对齐。
 */
export const SERVER_REGRESSION_CATALOG: RegressionCatalogCase[] = [
  {
    id: 'IDP-001',
    api: '任意 /idip/v1/*',
    servicePurpose: 'idipMiddleware · idipClientAllowed：非公网 IP 403',
    verify: 'RemoteAddr 公网 → 403',
    goTest: 'TestSmoke_IDIP_ForbiddenFromPublicIP',
    docRef: '§I IDP-001',
  },
  {
    id: 'TSK-S-006',
    api: 'POST /idip/v1/tasks/tier-policy',
    servicePurpose: 'SetTaskTierPolicy；ListActiveTaskDefs / activeCount',
    verify: '开 P1 后 active 增多；关 P0 后 P0 档为 0',
    goTest: 'TestIdipTaskTierPolicy_TogglesP1',
    docRef: '§L TSK-S-006',
  },
  {
    id: 'TSK-A-001',
    api: 'GET /idip/v1/tasks/definitions',
    servicePurpose: 'handleIdipTaskDefinitions → 全量 tasks 目录',
    verify: 'tasks 条数 ≥40',
    goTest: 'TestIdipTaskDefinitions_ReturnsCatalog',
    docRef: '§L TSK-A-001',
  },
  {
    id: 'TSK-A-002',
    api: 'POST /idip/v1/tasks/definition/upsert',
    servicePurpose: 'UpsertTaskOverride 热改 rewardGold；GET 读回',
    verify: 'rewardGold +1 后 definitions 一致并还原',
    goTest: 'TestIdipTaskDefinitionUpsert_Readback',
    docRef: '§L TSK-A-002',
  },
  {
    id: 'TSK-S-001',
    api: 'POST /api/v1/tasks/claim',
    servicePurpose: 'requireBearerAccountID',
    verify: '无 Bearer → 401 / code 1406',
    goTest: 'TestTasksClaim_NoBearer',
    docRef: '§L TSK-S-001',
  },
  {
    id: 'TSK-S-welfare',
    api: 'GET /api/v1/tasks/welfare',
    servicePurpose: '游客 Bearer 拉 welfare + signin7d + tasks[]',
    verify: 'code=0；todayYmd>0；canClaim',
    goTest: 'TestTasksWelfare_GuestAuth',
    docRef: '§L 游客 welfare',
  },
  {
    id: 'TSK-S-002',
    api: 'POST /api/v1/tasks/claim play_daily_60s',
    servicePurpose: 'TaskService.Claim 进度不足',
    verify: '未上报活跃 → 1421',
    goTest: 'TestTasksClaim_Play60s_NotClaimable',
    docRef: '§L TSK-S-002',
  },
  {
    id: 'TSK-S-004',
    api: 'POST /api/v1/tasks/claim daily_free_claim',
    servicePurpose: 'Claim → GoldLedger.ApplyGold',
    verify: '首次 grantedGold=50',
    goTest: 'TestTasksClaim_DailyFree',
    docRef: '§L TSK-S-004',
  },
  {
    id: 'TSK-S-003',
    api: 'POST /api/v1/tasks/claim daily_free_claim',
    servicePurpose: '重复领取',
    verify: '第二次 → 1422',
    goTest: 'TestTasksClaim_DailyFree',
    docRef: '§L TSK-S-003',
  },
  {
    id: 'TSK-S-007',
    api: 'POST /api/v1/tasks/claim daily_invite',
    servicePurpose: '无邀请进度',
    verify: '→ 1421',
    goTest: 'TestTasksClaim_DailyInvite_NotClaimable',
    docRef: '§L TSK-S-007',
  },
  {
    id: 'TSK-S-visit',
    api: 'POST /api/v1/tasks/report page_view',
    servicePurpose: 'OnPageView → daily_visit_welfare 进度',
    verify: 'welfare 响应含 daily_visit_welfare',
    goTest: 'TestTasksReport_PageView',
    docRef: '§L 访问福利页',
  },
  {
    id: 'TSK-S-play60',
    api: '（单元）OnRankActivity',
    servicePurpose: 'play_daily_60s 进度达 claimable',
    verify: 'Report 65s 后 status=claimable',
    goTest: 'TestTaskService_Play60sProgress',
    docRef: 'task_service_test · 支撑 TSK-C-003',
  },
  {
    id: 'TSK-S-signin',
    api: '（单元）signin_7d',
    servicePurpose: '新账号 signin7d.canClaim',
    verify: 'canClaim=true',
    goTest: 'TestTaskService_Signin7dClaimable',
    docRef: 'task_service_test',
  },
  {
    id: 'TSK-S-free',
    api: '（单元）daily_free_claim',
    servicePurpose: 'daily_free_claim 初始 claimable',
    verify: 'status=claimable',
    goTest: 'TestTaskService_DailyFreeClaimable',
    docRef: 'task_service_test',
  },
  {
    id: 'TSK-catalog',
    api: '（单元）tasks_welfare.json',
    servicePurpose: 'BuildFullTaskCatalog',
    verify: 'catalog≥40',
    goTest: 'TestBuildFullTaskCatalog_Counts',
    docRef: 'task_catalog_test',
  },
  {
    id: 'TSK-tier',
    api: '（单元）ListActiveTaskDefs',
    servicePurpose: 'TaskTierPolicy 过滤档位',
    verify: 'P0/P1 开关',
    goTest: 'TestTaskTierPolicy_FiltersList',
    docRef: 'task_catalog_test',
  },
  {
    id: 'RNK-S-activity',
    api: '（单元）ReportActivityPlay',
    servicePurpose: 'rank/activity 累计 activeScore',
    verify: '同 account 多次上报累加',
    goTest: 'TestReportActivityPlay_AccumulatesByAccountID',
    docRef: 'rank_activity_test · 支撑 TSK-C-003',
  },
  {
    id: 'FAV-S-001',
    api: 'POST/GET/DELETE /api/v1/games/favorite*',
    servicePurpose: 'GameFavoriteStore · 游客 Bearer 增删查',
    verify: 'add → list 含 gameId → delete 后不含',
    goTest: 'TestGameFavorite_AddListRemove',
    docRef: 'game_favorite_handlers_test · 对齐 FAV-I-*',
  },
  {
    id: 'FAV-S-002',
    api: '（单元）GameFavoriteService 内存 Store',
    servicePurpose: 'Add/List/Remove/IsFavorite/FavoriteSet',
    verify: '不依赖 MySQL；空 gameId → ErrGameFavoriteEmptyGameID',
    goTest: 'TestGameFavoriteService_AddListRemove',
    docRef: 'game_favorite_test · 支撑 FAV-S-001',
  },
];
