#!/usr/bin/env bash
# Xinglan Wujie 官网绿色部署 → /wwwroot/OfficialSite ，默认 http://<主机>:6060/
#
#   bash tools/OfficialSite/scripts/deploy-official-site.sh
#
# 环境变量：
#   DEPLOY_ROOT      默认 /wwwroot/OfficialSite
#   WEB_ROOT         默认 $DEPLOY_ROOT/www
#   NGINX_PREFIX     默认 $DEPLOY_ROOT/nginx
#   WEB_HTTP_PORT    默认 6060
#   VERIFY_HOST      冒烟测试主机（默认 192.168.75.99）
#
set -euo pipefail

log() { echo "[deploy-official-site] $*"; }
die() { echo "[deploy-official-site] FAIL: $*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
SITE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
[[ -f "$SITE_DIR/index.html" ]] || die "index.html not found under $SITE_DIR"

REPO_ROOT="${REPO_ROOT:-}"
if [[ -z "$REPO_ROOT" ]]; then
  if [[ -d "$SITE_DIR/../../release" || -d "$SITE_DIR/../../tools/nginx" ]]; then
    REPO_ROOT="$(cd "$SITE_DIR/../.." && pwd)"
  else
    REPO_ROOT="$SITE_DIR"
  fi
fi

DEPLOY_ENV="$SCRIPT_DIR/deploy-env.local.sh"
DEFAULT_ENV="$SCRIPT_DIR/deploy-env.local.example.sh"
if [[ -f "$DEPLOY_ENV" ]]; then
  log "source $DEPLOY_ENV"
  # shellcheck disable=SC1090
  source "$DEPLOY_ENV"
elif [[ -f "$DEFAULT_ENV" ]]; then
  log "source defaults: $DEFAULT_ENV"
  # shellcheck disable=SC1090
  source "$DEFAULT_ENV"
fi

DEPLOY_ROOT="${DEPLOY_ROOT:-/wwwroot/OfficialSite}"
WEB_ROOT="${WEB_ROOT:-$DEPLOY_ROOT/www}"
NGINX_PREFIX="${NGINX_PREFIX:-$DEPLOY_ROOT/nginx}"
WEB_HTTP_PORT="${WEB_HTTP_PORT:-6060}"
VERIFY_HOST="${VERIFY_HOST:-192.168.75.99}"

if [[ "$WEB_HTTP_PORT" == "80" || "$WEB_HTTP_PORT" == "443" ]] && [[ $EUID -ne 0 ]]; then
  die "port $WEB_HTTP_PORT requires root; use WEB_HTTP_PORT=6060 or run with sudo"
fi

SITE_URL="http://${VERIFY_HOST}:${WEB_HTTP_PORT}"

install_static() {
  need_cmd mkdir
  need_cmd cp
  mkdir -p "$WEB_ROOT"
  rm -rf "${WEB_ROOT:?}"/*
  cp -a "$SITE_DIR/index.html" "$SITE_DIR/style.css" "$SITE_DIR/i18n.js" "$WEB_ROOT/"
  if [[ -d "$SITE_DIR/privacy" ]]; then
    cp -a "$SITE_DIR/privacy" "$WEB_ROOT/"
  fi
  chmod -R a+rX "$WEB_ROOT" 2>/dev/null || true
  log "static → $WEB_ROOT"
}

stop_green_nginx() {
  if [[ -f "$NGINX_PREFIX/logs/nginx.pid" ]]; then
    nginx -p "$NGINX_PREFIX" -s quit 2>/dev/null || true
    sleep 1
  fi
}

port_in_use() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn 2>/dev/null | grep -q ":${port} "
  elif command -v netstat >/dev/null 2>&1; then
    netstat -ltn 2>/dev/null | grep -q ":${port} "
  else
    return 1
  fi
}

render_nginx() {
  local tpl="$REPO_ROOT/tools/nginx/official-site-green-http.conf"
  local out="$NGINX_PREFIX/conf/nginx.conf"
  [[ -f "$tpl" ]] || die "template missing: $tpl"
  need_cmd sed
  mkdir -p "$NGINX_PREFIX"/{conf,logs}
  cp -f "$REPO_ROOT/tools/nginx/mime.types" "$NGINX_PREFIX/conf/mime.types"
  sed \
    -e "s|__NGINX_PREFIX__|${NGINX_PREFIX}|g" \
    -e "s|__WEB_ROOT__|${WEB_ROOT}|g" \
    -e "s|__HTTP_PORT__|${WEB_HTTP_PORT}|g" \
    "$tpl" >"$out"
  log "nginx conf → $out"
}

start_green_nginx() {
  command -v nginx >/dev/null 2>&1 || die "nginx not installed"
  if port_in_use "$WEB_HTTP_PORT"; then
    local pid_file="$NGINX_PREFIX/logs/nginx.pid"
    if [[ -f "$pid_file" ]] && kill -0 "$(cat "$pid_file")" 2>/dev/null; then
      log "reload existing green nginx on :$WEB_HTTP_PORT"
      nginx -p "$NGINX_PREFIX" -s reload 2>/dev/null || true
      return 0
    fi
    die "port $WEB_HTTP_PORT already in use by another process"
  fi
  stop_green_nginx
  nginx -p "$NGINX_PREFIX" -t -c conf/nginx.conf || die "nginx -t failed"
  nginx -p "$NGINX_PREFIX" -c conf/nginx.conf
  log "green nginx started pid=$(cat "$NGINX_PREFIX/logs/nginx.pid" 2>/dev/null || echo '?')"
}

write_deploy_info() {
  mkdir -p "$DEPLOY_ROOT"
  cat >"$DEPLOY_ROOT/deploy-info.env" <<EOF
# Generated by deploy-official-site.sh
export DEPLOY_ROOT='$DEPLOY_ROOT'
export NGINX_PREFIX='$NGINX_PREFIX'
export WEB_ROOT='$WEB_ROOT'
export WEB_HTTP_PORT='$WEB_HTTP_PORT'
export SITE_URL='$SITE_URL'
EOF
  log "deploy info → $DEPLOY_ROOT/deploy-info.env"
}

smoke_test() {
  need_cmd curl
  curl -fsS --max-time 8 "$SITE_URL/" | grep -qiE 'Xinglan Wujie|星澜' \
    || die "smoke failed: $SITE_URL/"
  log "smoke OK $SITE_URL/"
}

main() {
  log "REPO_ROOT=$REPO_ROOT"
  log "DEPLOY_ROOT=$DEPLOY_ROOT WEB_ROOT=$WEB_ROOT port=$WEB_HTTP_PORT"
  log "SITE_URL=$SITE_URL"

  install_static
  render_nginx
  start_green_nginx
  write_deploy_info
  smoke_test

  log "OK  打开 $SITE_URL/"
  log "    启停: bash $SCRIPT_DIR/official-site-ctl.sh {start|stop|status}"
}

main "$@"
