#!/usr/bin/env bash
# idip-webclient：生成运营凭据，写入 release/configs/starcrystal.json（仅 idip 段），并在 scripts_encrypt/encrypt 落盘。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ENCRYPT_BIN="${SCRIPT_DIR}/bin/encrypt-idip-operator"
readonly DEFAULT_CONFIG_PATH="$(cd "${SCRIPT_DIR}/../../.." && pwd)/release/configs/starcrystal.json"
readonly LOCAL_PLAIN_FILE="${SCRIPT_DIR}/encrypt/idip-operator.plain.txt"
readonly LOCAL_ENCRYPTED_FILE="${SCRIPT_DIR}/encrypt/idip-operator.encrypted.json"
readonly DEFAULT_OPERATOR_PASSWORD='jgyjgyjgy'

_idip_require_cmds() {
  local missing=()
  for cmd in openssl base64 od mktemp; do
    command -v "${cmd}" >/dev/null 2>&1 || missing+=("${cmd}")
  done
  [[ -r /dev/urandom ]] || missing+=("/dev/urandom")
  if ((${#missing[@]})); then
    echo "Missing: ${missing[*]}" >&2
    return 1
  fi
  command -v jq >/dev/null 2>&1 || command -v python3 >/dev/null 2>&1 || {
    echo "Need jq or python3 to update starcrystal.json" >&2
    return 1
  }
}

_idip_json_field() {
  local json="$1" field="$2"
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "${json}" | jq -r ".${field}"
    return 0
  fi
  python3 -c 'import json, sys; print(json.loads(sys.argv[1])[sys.argv[2]])' "${json}" "${field}"
}

_idip_openssl_gcm_ok() {
  local z32 z12
  z32="$(printf '00%.0s' {1..64})"
  z12="$(printf '00%.0s' {1..24})"
  echo -n x | openssl enc -aes-256-gcm -e -K "${z32}" -iv "${z12}" -nosalt -out /dev/null 2>/dev/null
}

_idip_ensure_encrypt_bin() {
  if [[ -x "${ENCRYPT_BIN}" ]]; then
    return 0
  fi
  if [[ -f "${ENCRYPT_BIN}" ]]; then
    chmod +x "${ENCRYPT_BIN}" 2>/dev/null || true
    [[ -x "${ENCRYPT_BIN}" ]] && return 0
  fi
  local gz="${SCRIPT_DIR}/bin/encrypt-idip-operator.gz"
  if [[ -f "${gz}" ]]; then
    if command -v gunzip >/dev/null 2>&1; then
      gunzip -c "${gz}" >"${ENCRYPT_BIN}"
    else
      gzip -dc "${gz}" >"${ENCRYPT_BIN}"
    fi
    chmod +x "${ENCRYPT_BIN}"
    if [[ -s "${ENCRYPT_BIN}" && -x "${ENCRYPT_BIN}" ]]; then
      return 0
    fi
  fi
  return 1
}

_idip_resolve_encrypt_method() {
  if _idip_ensure_encrypt_bin; then
    echo bin
    return 0
  fi
  if _idip_openssl_gcm_ok; then
    echo openssl
    return 0
  fi
  echo "Need ${ENCRYPT_BIN} or OpenSSL 1.1+ GCM" >&2
  ls -la "${SCRIPT_DIR}/bin/" 2>&1 >&2 || true
  return 1
}

_idip_encrypt_openssl() {
  local username="$1" password="$2" cipher_key_b64="$3"
  local key_file nonce_file ct_file enc_body
  key_file="$(mktemp)"
  nonce_file="$(mktemp)"
  ct_file="$(mktemp)"
  enc_body="$(mktemp)"
  trap 'rm -f "${key_file}" "${nonce_file}" "${ct_file}" "${enc_body}"' RETURN
  printf '%s' "${cipher_key_b64}" | base64 -d >"${key_file}"
  if [[ "$(wc -c <"${key_file}")" -ne 32 ]]; then
    echo "cipher key must be 32 bytes" >&2
    return 1
  fi
  local key_hex nonce_hex
  key_hex="$(od -An -tx1 "${key_file}" | tr -d ' \n')"
  openssl rand 12 >"${nonce_file}"
  nonce_hex="$(od -An -tx1 "${nonce_file}" | tr -d ' \n')"
  if ! printf '%s' "${password}" | openssl enc -aes-256-gcm -e \
    -K "${key_hex}" -iv "${nonce_hex}" -nosalt -out "${ct_file}" 2>/dev/null; then
    echo "openssl enc failed" >&2
    return 1
  fi
  cat "${nonce_file}" "${ct_file}" | base64 | tr -d '\n' >"${enc_body}"
  printf '{\n  "username": "%s",\n  "passwordEnc": "v1:%s"\n}\n' "${username}" "$(cat "${enc_body}")"
}

_idip_encrypt() {
  local method="$4"
  if [[ "${method}" == bin ]]; then
    "${ENCRYPT_BIN}" -username "$1" -password "$2" -cipher-key-base64 "$3"
  else
    _idip_encrypt_openssl "$1" "$2" "$3"
  fi
}

_idip_write_local_files() {
  local username="$1" password="$2" cipher_b64="$3" op_json="$4"
  mkdir -p "${SCRIPT_DIR}/encrypt"
  {
    echo "# Generated by encrypt-idip-operator.sh — keep secret"
    echo "IDIP_OPERATOR_USERNAME=${username}"
    echo "IDIP_OPERATOR_PASSWORD=${password}"
    echo "IDIP_OPERATOR_CIPHER_KEY=${cipher_b64}"
  } >"${LOCAL_PLAIN_FILE}"
  printf '%s\n' "${op_json}" >"${LOCAL_ENCRYPTED_FILE}"
  chmod 777 "${LOCAL_PLAIN_FILE}" "${LOCAL_ENCRYPTED_FILE}" 2>/dev/null || true
  echo "Wrote ${LOCAL_PLAIN_FILE}" >&2
  echo "Wrote ${LOCAL_ENCRYPTED_FILE}" >&2
}

_idip_merge_config() {
  local cfg_path="$1" cipher_b64="$2" op_json="$3"
  local username password_enc tmp
  username="$(_idip_json_field "${op_json}" username)"
  password_enc="$(_idip_json_field "${op_json}" passwordEnc)"
  if command -v jq >/dev/null 2>&1; then
    tmp="$(mktemp)"
    jq \
      --arg ck "${cipher_b64}" \
      --arg un "${username}" \
      --arg pe "${password_enc}" \
      '.idip //= {} | .idip.operatorCipherKey = $ck | .idip.operators = [{username: $un, passwordEnc: $pe}]' \
      "${cfg_path}" >"${tmp}"
    mv "${tmp}" "${cfg_path}"
  else
    python3 - "${cfg_path}" "${cipher_b64}" "${username}" "${password_enc}" <<'PY'
import json
import sys

cfg_path, cipher_b64, username, password_enc = sys.argv[1:5]
with open(cfg_path, encoding="utf-8") as f:
    data = json.load(f)
data.setdefault("idip", {})
data["idip"]["operatorCipherKey"] = cipher_b64
data["idip"]["operators"] = [{"username": username, "passwordEnc": password_enc}]
with open(cfg_path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write("\n")
PY
  fi
  echo "Updated ${cfg_path} (idip.operatorCipherKey + idip.operators only)" >&2
}

_idip_require_cmds || exit 1
if ! ENCRYPT_METHOD="$(_idip_resolve_encrypt_method)"; then
  exit 1
fi

CONFIG_PATH="${IDIP_CONFIG_PATH:-${DEFAULT_CONFIG_PATH}}"
readonly DEFAULT_USERNAME="${IDIP_OPERATOR_USERNAME:-holyjing}"
DEFAULT_PASSWORD="${IDIP_OPERATOR_PASSWORD:-${DEFAULT_OPERATOR_PASSWORD}}"

if [[ -n "${IDIP_OPERATOR_CIPHER_KEY:-}" ]]; then
  DEFAULT_CIPHER_KEY_B64="${IDIP_OPERATOR_CIPHER_KEY}"
else
  DEFAULT_CIPHER_KEY_B64="$(openssl rand -base64 32 | tr -d '\n')"
fi

if [[ ! -f "${CONFIG_PATH}" ]]; then
  echo "Config not found: ${CONFIG_PATH}" >&2
  exit 1
fi

out="$(_idip_encrypt "${DEFAULT_USERNAME}" "${DEFAULT_PASSWORD}" "${DEFAULT_CIPHER_KEY_B64}" "${ENCRYPT_METHOD}")"

_idip_write_local_files "${DEFAULT_USERNAME}" "${DEFAULT_PASSWORD}" "${DEFAULT_CIPHER_KEY_B64}" "${out}"
_idip_merge_config "${CONFIG_PATH}" "${DEFAULT_CIPHER_KEY_B64}" "${out}"

echo "${out}"
